/**
 * Language-pack generation: turn a canonical source catalog plus a target
 * catalog into an installable Harness plugin
 * (`package.json`, `index.js`, `client.js`, `cordis.patch.yml`).
 */

import fs from 'node:fs'
import path from 'node:path'
import { CATALOG_VERSION, normalizeCatalog, writeCatalog } from './catalog.mjs'
import { comparePlaceholders } from './placeholders.mjs'
import { percent, sortedKeys, writeText } from './util.mjs'

/** Build the browser-half module that registers the language and dictionaries. */
export function buildClientSource({ id, locale, label, fallback, namespaces }) {
  const dictionaries = JSON.stringify(namespaces, null, 2)
  return `/**
 * ${label} language pack for DeepSeek Harness.
 * Generated by tools/dsh-locale — edit locales/${locale}.json and re-run
 * \`npm run locale:update\` instead of editing this file by hand.
 */
window.__ModuleLoader__.load({
  id: '${id}',
  factory() {
    return {
      inject: ['locale'],
      apply(ctx) {
        ctx.effect(
          () => ctx.locale.addLanguage({ id: '${locale}', label: ${JSON.stringify(label)}, fallback: '${fallback}' }),
          'master-cas: register ${label} language'
        )

        /* One dictionary per Harness client locale namespace. */
        const dictionaries = ${dictionaries}

        for (const [namespace, dictionary] of Object.entries(dictionaries)) {
          ctx.effect(
            () => ctx.locale.register(namespace, '${locale}', dictionary),
            \`master-cas: ${label} dictionary \${namespace}\`
          )
        }
      }
    }
  }
})
`
}

/** Build the host-half companion module. */
export function buildIndexSource() {
  return '/** Host companion for the generated language bundle. */\nexport function apply() {}\n'
}

/** Build the package manifest. */
export function buildPackageJson({ name, id, version, description, locale, label, homepage }) {
  return `${JSON.stringify(
    {
      name,
      version,
      description,
      license: 'MIT',
      type: 'module',
      main: 'index.js',
      exports: {
        '.': './index.js',
        './client': './client.js',
      },
      dsh: {
        bundle: { patch: './cordis.patch.yml' },
        client: { platform: 'web' },
      },
      author: {
        name: 'Master-Cas',
        url: 'https://github.com/Master-Cas',
      },
      repository: {
        type: 'git',
        url: 'https://github.com/Master-Cas/DeepSeek_Harness_Tools.git',
      },
      ...(homepage ? { homepage } : {}),
      keywords: ['deepseek-harness', 'language-pack', locale],
      'master-cas': { generated: true, locale, label, pluginId: id },
    },
    null,
    2,
  )}\n`
}

/** Build the cordis patch inserting the bundle into a profile. */
export function buildCordisPatch({ id, name }) {
  return `- insert:\n    - id: ${id.replace(/^@/, '').replace(/[^a-zA-Z0-9-]+/g, '-')}\n      name: '${name}'\n`
}

/** Build every plugin file for a catalog. */
export function buildPluginFiles({ name, id, version = '0.1.0', description, locale, label, fallback = 'en', namespaces, homepage }) {
  return {
    'package.json': buildPackageJson({ name, id, version, description, locale, label, homepage }),
    'index.js': buildIndexSource(),
    'client.js': buildClientSource({ id, locale, label, fallback, namespaces }),
    'cordis.patch.yml': buildCordisPatch({ id, name }),
  }
}

/** Write the generated files into `dir`, returning the directory. */
export function writePluginFiles(dir, files) {
  for (const [file, content] of Object.entries(files)) {
    writeText(path.join(dir, file), content)
  }
  return dir
}

/**
 * Compute which source keys still need a translation.
 * Existing translations are reused when non-empty and placeholder-safe.
 */
export function planTranslationMemory(source, existing) {
  const existingCatalog = existing ? normalizeCatalog(existing) : { namespaces: {} }
  const reused = {}
  const pending = []

  for (const namespace of sortedKeys(source.namespaces)) {
    reused[namespace] = {}
    for (const key of sortedKeys(source.namespaces[namespace])) {
      const value = existingCatalog.namespaces?.[namespace]?.[key]
      if (typeof value === 'string' && value !== '') {
        const placeholders = comparePlaceholders(source.namespaces[namespace][key], value)
        if (placeholders.ok) {
          reused[namespace][key] = value
          continue
        }
      }
      pending.push({
        id: `${namespace}\u0000${key}`,
        namespace,
        key,
        text: source.namespaces[namespace][key],
      })
    }
  }
  return { reused, pending }
}

/**
 * Generate a language pack.
 *
 * @param {object} options generation options.
 * @param {object} options.source normalized English source catalog.
 * @param {object} [options.existing] existing target catalog (translation memory).
 * @param {string} options.locale target locale id.
 * @param {string} options.label target language display label.
 * @param {Function} [options.translate] translation runner `(entries) => Promise<Map>`.
 * @param {boolean} [options.noTranslate] copy English instead of calling the API.
 * @param {boolean} [options.dryRun] plan only; no API calls, no writes.
 * @param {object} [options.plugin] plugin identity `{ name, id, version, description, outDir }`.
 * @param {string} [options.catalogFile] canonical target catalog path to write.
 * @param {string} [options.sourceRef] source reference label stored in the catalog.
 * @returns {Promise<object>} generation result.
 */
export async function generateLanguagePack(options) {
  const source = normalizeCatalog(options.source)
  const { reused, pending } = planTranslationMemory(source, options.existing)
  const warnings = []

  if (options.dryRun) {
    return {
      dryRun: true,
      locale: options.locale,
      label: options.label,
      reused: Object.values(reused).reduce((sum, dict) => sum + Object.keys(dict).length, 0),
      pending: pending.length,
      sources: source,
      reusedNamespaces: reused,
      pendingEntries: pending,
      warnings,
    }
  }

  const translated = new Map()
  if (options.noTranslate) {
    for (const entry of pending) translated.set(entry.id, entry.text)
  } else if (pending.length) {
    if (typeof options.translate !== 'function') {
      throw new Error('no translation runner configured; pass --no-translate to scaffold from English')
    }
    const result = await options.translate(pending)
    for (const entry of pending) {
      const value = result.get(entry.id)
      if (typeof value !== 'string' || value === '') {
        warnings.push(`unresolved translation for ${entry.namespace}.${entry.key}; copied English`)
        translated.set(entry.id, entry.text)
      } else {
        translated.set(entry.id, value)
      }
    }
  }

  const namespaces = {}
  for (const namespace of sortedKeys(source.namespaces)) {
    namespaces[namespace] = {}
    for (const key of sortedKeys(source.namespaces[namespace])) {
      const id = `${namespace}\u0000${key}`
      if (Object.prototype.hasOwnProperty.call(reused[namespace] ?? {}, key)) {
        namespaces[namespace][key] = reused[namespace][key]
      } else {
        namespaces[namespace][key] = translated.get(id) ?? source.namespaces[namespace][key]
      }
    }
  }

  const catalog = {
    version: CATALOG_VERSION,
    locale: options.locale,
    label: options.label,
    fallback: options.fallback ?? 'en',
    source: options.sourceRef ?? 'locales/source-en.json',
    namespaces,
  }

  const files = buildPluginFiles({
    name: options.plugin.name,
    id: options.plugin.id,
    version: options.plugin.version,
    description: options.plugin.description,
    locale: options.locale,
    label: options.label,
    fallback: options.fallback ?? 'en',
    namespaces,
    homepage: options.plugin.homepage,
  })

  let pluginDir
  if (options.plugin.dir) {
    pluginDir = writePluginFiles(options.plugin.dir, files)
  }
  if (options.catalogFile) writeCatalog(options.catalogFile, catalog)

  return {
    dryRun: false,
    locale: options.locale,
    label: options.label,
    catalog,
    files,
    pluginDir,
    reused: Object.values(reused).reduce((sum, dict) => sum + Object.keys(dict).length, 0),
    translated: pending.length,
    pending: 0,
    coverage: percent(1),
    warnings,
  }
}

/** Read an existing plugin directory's client.js into a catalog (if present). */
export function readPluginCatalog(pluginDir) {
  const clientFile = path.join(pluginDir, 'client.js')
  return fs.existsSync(clientFile) ? clientFile : undefined
}
