/**
 * Language-pack generation: turn a canonical source catalog plus a target
 * catalog into an installable Harness plugin
 * (`package.json`, `index.js`, `client.js`, `cordis.patch.yml`).
 */

import fs from 'node:fs'
import path from 'node:path'
import { CATALOG_VERSION, normalizeCatalog, writeCatalog } from './catalog.mjs'
import { comparePlaceholders } from './placeholders.mjs'
import {
  hash,
  percent,
  sortedKeys,
  validateLocaleId,
  validatePackageName,
  validatePluginId,
  validateTextField,
  validateVersion,
  writeText,
} from './util.mjs'

const MASTER_CAS_LICENSE = fs.readFileSync(new URL('../../LICENSE', import.meta.url), 'utf8')

/** Build the browser-half module that registers the language and dictionaries. */
export function buildClientSource({ id, locale, label, fallback, namespaces }) {
  validatePluginId(id)
  validateLocaleId(locale)
  validateTextField(label, 'language label')
  validateLocaleId(fallback, 'fallback')
  const dictionaries = JSON.stringify(namespaces, null, 2)
  const idLiteral = JSON.stringify(id)
  const localeLiteral = JSON.stringify(locale)
  const labelLiteral = JSON.stringify(label)
  const fallbackLiteral = JSON.stringify(fallback)
  const languageEffect = JSON.stringify(`master-cas: register ${label} language`)
  return `/**
 * Language pack for DeepSeek Harness.
 * Original tooling and generator author: Master-Cas — https://github.com/Master-Cas
 * Original repository: https://github.com/Master-Cas/DeepSeek_Harness_Tools
 * License: Master-Cas Personal Use License v1.0
 * Generated by tools/dsh-locale; edit the canonical locale catalog and regenerate.
 */
window.__ModuleLoader__.load({
  id: ${idLiteral},
  factory() {
    return {
      inject: ['locale'],
      apply(ctx) {
        ctx.effect(
          () => ctx.locale.addLanguage({ id: ${localeLiteral}, label: ${labelLiteral}, fallback: ${fallbackLiteral} }),
          ${languageEffect}
        )

        /* One dictionary per Harness client locale namespace. */
        const dictionaries = ${dictionaries}

        for (const [namespace, dictionary] of Object.entries(dictionaries)) {
          ctx.effect(
            () => ctx.locale.register(namespace, ${localeLiteral}, dictionary),
            \`master-cas: dictionary \${namespace}\`
          )
        }
      }
    }
  }
})
`
}

/** Build the host-half companion module. */
export function buildIndexSource() {
  return '/** Host companion for a DeepSeek Harness language bundle generated by dsh-locale. Original tooling author: Master-Cas — https://github.com/Master-Cas */\nexport function apply() {}\n'
}

/** Build the package manifest. */
export function buildPackageJson({ name, id, version, description, locale, label, homepage }) {
  validatePackageName(name)
  validatePluginId(id)
  validateVersion(version)
  validateLocaleId(locale)
  validateTextField(label, 'language label')
  return `${JSON.stringify(
    {
      name,
      version,
      description,
      license: 'SEE LICENSE IN LICENSE',
      type: 'module',
      main: 'index.js',
      exports: {
        '.': './index.js',
        './client': './client.js',
      },
      dsh: {
        bundle: { patch: './cordis.patch.yml' },
        client: { platform: 'web' },
      },
      author: {
        name: 'Master-Cas',
        url: 'https://github.com/Master-Cas',
      },
      maintainers: [
        {
          name: 'Master-Cas',
          url: 'https://github.com/Master-Cas',
        },
      ],
      repository: {
        type: 'git',
        url: 'https://github.com/Master-Cas/DeepSeek_Harness_Tools.git',
      },
      ...(homepage ? { homepage } : {}),
      keywords: ['deepseek-harness', 'language-pack', locale],
      'master-cas': {
        generated: true,
        locale,
        label,
        pluginId: id,
        originalAuthor: 'Master-Cas',
        originalRepository: 'https://github.com/Master-Cas/DeepSeek_Harness_Tools',
        license: 'Master-Cas Personal Use License v1.0',
        commercialUse: 'Requires prior written commercial agreement with Master-Cas',
      },
    },
    null,
    2,
  )}\n`
}

/** Build the cordis patch inserting the bundle into a profile. */
export function buildCordisPatch({ id, name }) {
  validatePluginId(id)
  validatePackageName(name)
  const patchId = id.replace(/^@/, '').replace(/[^a-zA-Z0-9-]+/g, '-')
  return `- insert:\n    - id: ${JSON.stringify(patchId)}\n      name: ${JSON.stringify(name)}\n`
}

/** Build every plugin file for a catalog. */
export function buildPluginFiles({ name, id, version = '0.1.0', description, locale, label, fallback = 'en', namespaces, homepage }) {
  validatePackageName(name)
  validatePluginId(id)
  validateVersion(version)
  validateLocaleId(locale)
  validateLocaleId(fallback, 'fallback')
  validateTextField(label, 'language label')
  return {
    'package.json': buildPackageJson({ name, id, version, description, locale, label, homepage }),
    'index.js': buildIndexSource(),
    'client.js': buildClientSource({ id, locale, label, fallback, namespaces }),
    'cordis.patch.yml': buildCordisPatch({ id, name }),
    'LICENSE': MASTER_CAS_LICENSE,
  }
}

/** Write the generated files into `dir`, returning the directory. */
export function writePluginFiles(dir, files) {
  fs.mkdirSync(dir, { recursive: true })
  const realDir = fs.realpathSync(dir)
  for (const [file, content] of Object.entries(files)) {
    const target = path.join(dir, file)
    if (fs.existsSync(target) && fs.lstatSync(target).isSymbolicLink()) {
      throw new Error(`refusing to write plugin file through symbolic link: ${file}`)
    }
    const realParent = fs.realpathSync(path.dirname(target))
    if (realParent !== realDir) throw new Error(`plugin file parent escaped output directory: ${file}`)
    writeText(target, content)
  }
  return dir
}

/** Deterministic SHA-256 identity for one English source string. */
export function sourceEntryHash(value) {
  return hash(String(value))
}

/** Hash every current source entry using a stable namespace/key ordering. */
export function buildSourceHashes(source) {
  const normalized = normalizeCatalog(source)
  const hashes = {}
  for (const namespace of sortedKeys(normalized.namespaces)) {
    hashes[namespace] = {}
    for (const key of sortedKeys(normalized.namespaces[namespace])) {
      hashes[namespace][key] = sourceEntryHash(normalized.namespaces[namespace][key])
    }
  }
  return hashes
}

/** Metadata persisted with target catalogs so reuse is verifiable. */
export function buildTranslationMeta(existing, sourceHashes, legacyUnverified = []) {
  const prior = existing ? normalizeCatalog(existing).meta : {}
  const meta = { ...prior }
  delete meta.sourceHashes
  delete meta.sourceHashAlgorithm
  delete meta.legacyUnverified
  meta.sourceHashAlgorithm = 'sha256'
  meta.sourceHashes = sourceHashes
  if (legacyUnverified.length) meta.legacyUnverified = [...legacyUnverified].sort()
  return meta
}

/**
 * Compute which source keys still need a translation.
 * Existing translations are reusable only when placeholders are valid and a
 * stored source hash still matches. Pre-hash catalogs are migrated without a
 * mass retranslation, but every such reuse remains explicitly marked legacy.
 */
export function planTranslationMemory(source, existing) {
  const src = normalizeCatalog(source)
  const existingCatalog = existing ? normalizeCatalog(existing) : { namespaces: {}, meta: {} }
  const sourceHashes = buildSourceHashes(src)
  const priorHashes = existingCatalog.meta?.sourceHashes ?? {}
  const priorLegacy = new Set(existingCatalog.meta?.legacyUnverified ?? [])
  const reused = {}
  const pending = []
  const modified = []
  const legacyUnverified = []

  for (const namespace of sortedKeys(src.namespaces)) {
    reused[namespace] = {}
    for (const key of sortedKeys(src.namespaces[namespace])) {
      const id = `${namespace}\u0000${key}`
      const text = src.namespaces[namespace][key]
      const value = existingCatalog.namespaces?.[namespace]?.[key]
      const currentHash = sourceHashes[namespace][key]
      const priorHash = priorHashes?.[namespace]?.[key]
      if (typeof value === 'string' && value !== '') {
        if (typeof priorHash === 'string' && priorHash !== currentHash) {
          const entry = { id, namespace, key, text, reason: 'source-changed', priorHash, currentHash }
          modified.push(entry)
          pending.push(entry)
          continue
        }
        const placeholders = comparePlaceholders(text, value)
        if (placeholders.ok) {
          reused[namespace][key] = value
          if (typeof priorHash !== 'string' || priorLegacy.has(id)) legacyUnverified.push(id)
          continue
        }
        pending.push({ id, namespace, key, text, reason: 'placeholder-mismatch' })
        continue
      }
      pending.push({ id, namespace, key, text, reason: value === '' ? 'empty' : 'missing' })
    }
  }
  return { reused, pending, sourceHashes, modified, legacyUnverified }
}

/**
 * Generate a language pack.
 *
 * @param {object} options generation options.
 * @param {object} options.source normalized English source catalog.
 * @param {object} [options.existing] existing target catalog (translation memory).
 * @param {string} options.locale target locale id.
 * @param {string} options.label target language display label.
 * @param {Function} [options.translate] translation runner `(entries) => Promise<Map>`.
 * @param {boolean} [options.noTranslate] copy English instead of calling the API.
 * @param {boolean} [options.dryRun] plan only; no API calls, no writes.
 * @param {object} [options.plugin] plugin identity `{ name, id, version, description, outDir }`.
 * @param {string} [options.catalogFile] canonical target catalog path to write.
 * @param {string} [options.sourceRef] source reference label stored in the catalog.
 * @returns {Promise<object>} generation result.
 */
export async function generateLanguagePack(options) {
  const source = normalizeCatalog(options.source)
  const { reused, pending, sourceHashes, modified, legacyUnverified } = planTranslationMemory(source, options.existing)
  const warnings = []
  if (modified.length) warnings.push(`${modified.length} translation(s) invalidated because the English source changed`)
  if (legacyUnverified.length) warnings.push(`${legacyUnverified.length} legacy translation(s) reused without historical source hashes`)

  if (options.dryRun) {
    return {
      dryRun: true,
      locale: options.locale,
      label: options.label,
      reused: Object.values(reused).reduce((sum, dict) => sum + Object.keys(dict).length, 0),
      pending: pending.length,
      sources: source,
      reusedNamespaces: reused,
      pendingEntries: pending,
      modified: modified.length,
      legacyReused: legacyUnverified.length,
      warnings,
    }
  }

  const translated = new Map()
  if (options.noTranslate) {
    for (const entry of pending) translated.set(entry.id, entry.text)
  } else if (pending.length) {
    if (typeof options.translate !== 'function') {
      throw new Error('no translation runner configured; pass --no-translate to scaffold from English')
    }
    const result = await options.translate(pending)
    for (const entry of pending) {
      const value = result.get(entry.id)
      if (typeof value !== 'string' || value === '') {
        warnings.push(`unresolved translation for ${entry.namespace}.${entry.key}; copied English`)
        translated.set(entry.id, entry.text)
      } else {
        translated.set(entry.id, value)
      }
    }
  }

  const namespaces = {}
  for (const namespace of sortedKeys(source.namespaces)) {
    namespaces[namespace] = {}
    for (const key of sortedKeys(source.namespaces[namespace])) {
      const id = `${namespace}\u0000${key}`
      if (Object.prototype.hasOwnProperty.call(reused[namespace] ?? {}, key)) {
        namespaces[namespace][key] = reused[namespace][key]
      } else {
        namespaces[namespace][key] = translated.get(id) ?? source.namespaces[namespace][key]
      }
    }
  }

  const catalog = {
    version: CATALOG_VERSION,
    locale: options.locale,
    label: options.label,
    fallback: options.fallback ?? 'en',
    source: options.sourceRef ?? 'locales/source-en.json',
    namespaces,
    meta: buildTranslationMeta(options.existing, sourceHashes, legacyUnverified),
  }

  const files = buildPluginFiles({
    name: options.plugin.name,
    id: options.plugin.id,
    version: options.plugin.version,
    description: options.plugin.description,
    locale: options.locale,
    label: options.label,
    fallback: options.fallback ?? 'en',
    namespaces,
    homepage: options.plugin.homepage,
  })

  let pluginDir
  if (options.plugin.dir) {
    pluginDir = writePluginFiles(options.plugin.dir, files)
  }
  if (options.catalogFile) writeCatalog(options.catalogFile, catalog)

  return {
    dryRun: false,
    locale: options.locale,
    label: options.label,
    catalog,
    files,
    pluginDir,
    reused: Object.values(reused).reduce((sum, dict) => sum + Object.keys(dict).length, 0),
    translated: pending.length,
    modified: modified.length,
    legacyReused: legacyUnverified.length,
    pending: 0,
    coverage: percent(1),
    warnings,
  }
}

/** Read an existing plugin directory's client.js into a catalog (if present). */
export function readPluginCatalog(pluginDir) {
  const clientFile = path.join(pluginDir, 'client.js')
  return fs.existsSync(clientFile) ? clientFile : undefined
}
