/** Spanish language pack for DeepSeek Harness. */
window.__ModuleLoader__.load({
  id: '@master-cas/deepseek-spanish',
  factory() {
    return {
      inject: ['locale'],
      apply(ctx) {
        ctx.effect(
          () => ctx.locale.addLanguage({ id: 'es', label: 'Español', fallback: 'en' }),
          'master-cas: register Spanish language'
        )

        const dictionaries = {
          common: {
            ok: 'Aceptar',
            cancel: 'Cancelar',
            close: 'Cerrar',
            copy: 'Copiar',
            copied: 'Copiado',
            'copy.failed': 'No se pudo copiar',
            'copy.value': 'Copiar valor',
            'copy.json': 'Copiar JSON',
            'copy.path': 'Copiar ruta de la propiedad',
            retry: 'Reintentar',
            loading: 'Cargando…',
            'load.failed': 'No se pudo cargar',
            submit: 'Enviar',
            submitting: 'Enviando…',
            next: 'Siguiente',
            previous: 'Anterior',
            skip: 'Omitir',
            delete: 'Eliminar',
            edit: 'Editar',
            save: 'Guardar',
            search: 'Buscar',
            more: 'Más',
            collapse: 'Contraer',
            expand: 'Expandir',
            back: 'Atrás',
            'brand.localBuild': 'Compilación local de DSH',
            unknown: 'Desconocido',
            none: 'Ninguno',
            truncated: 'Truncado',
            'markdown.footnotes': 'Notas al pie'
          },
          'settings.locale': {
            'language.title': 'Idioma'
          },
          'settings.theme': {
            'appearance.title': 'Apariencia',
            'appearance.light': 'Claro',
            'appearance.dark': 'Oscuro',
            'appearance.system': 'Sistema',
            'fontSize.title': 'Tamaño de fuente',
            'fontSize.description': 'Solo afecta el contenido de las conversaciones',
            'fontSize.unit': 'px',
            'fontSize.increase': 'Aumentar tamaño de fuente',
            'fontSize.decrease': 'Disminuir tamaño de fuente'
          },
          settings: {
            trigger: 'Configuración',
            title: 'Configuración',
            close: 'Cerrar',
            openDocument: 'Abrir archivo de configuración',
            'openDocument.error': 'No se pudo abrir el archivo de configuración',
            'general.nav': 'General',
            'connection.error': 'Desconectado',
            'connection.connecting': 'Reconectando',
            'connection.connected': 'Conectado',
            'connection.reconnect': 'Desconectado; reconectar ahora',
            'connection.restart': 'Reconectando; reconectar ahora',
            'desktop.update.available': 'Actualización',
            'desktop.update.checking': 'Buscando actualizaciones…',
            'desktop.update.ready': 'Instalar y reiniciar',
            'desktop.update.retry': 'Reintentar actualización'
          },
          sidebar: {
            'session.new': 'Nueva sesión',
            'session.new.label': 'Nueva sesión',
            'toggle.open': 'Abrir barra lateral',
            'toggle.collapse': 'Contraer barra lateral',
            'panels.label': 'Paneles globales'
          },
          workspace: {
            'group.ungrouped': 'Sin agrupar',
            'session.new': 'Nueva sesión',
            'section.workspaces': 'Espacios de trabajo',
            'section.sessions': 'Sesiones',
            'viewOptions.label': 'Opciones de vista',
            'groupBy.label': 'Agrupar por',
            'groupBy.workspace': 'Espacio de trabajo',
            'groupBy.workspaceTree': 'Árbol de espacios',
            'groupBy.flat': 'En una lista',
            'orderBy.label': 'Ordenar por',
            'orderBy.manual': 'Manual',
            'orderBy.updated': 'Última actualización',
            'sessions.collapse': 'Mostrar menos',
            'empty.none': 'Aún no hay sesiones',
            'empty.noMatches': 'Sin coincidencias',
            'workspace.add': 'Agregar espacio de trabajo',
            'search.sessions.aria': 'Buscar sesiones',
            'search.placeholder': 'Buscar sesiones…',
            'search.clear': 'Limpiar búsqueda',
            'search.pending': 'Buscando en el historial…',
            'search.noMatches': 'No hay sesiones coincidentes',
            'menu.addWorkspace': 'Agregar espacio de trabajo…',
            'picker.loading': 'Cargando espacios de trabajo…',
            rename: 'Renombrar',
            'rename.workspace.title': 'Renombrar espacio de trabajo',
            'rename.session.title': 'Renombrar sesión',
            'field.workspaceName': 'Nombre del espacio de trabajo',
            'field.sessionName': 'Nombre de la sesión',
            'delete.workspace': 'Eliminar espacio de trabajo',
            'menu.fork': 'Bifurcar sesión',
            'menu.archiveSession': 'Archivar sesión',
            'status.running': 'En ejecución',
            'status.idle': 'Inactivo',
            'status.waitingApproval': 'Esperando aprobación',
            'status.planReview': 'Plan pendiente de revisión',
            'status.waitingAnswer': 'Esperando respuesta',
            'status.completed': 'Completado',
            'time.now': 'ahora',
            'time.ago': 'hace {t}'
          },
          model: {
            'command.label': 'Modelo',
            'command.description': 'Selecciona el modelo para esta conversación',
            'trigger.fallback': 'Seleccionar modelo',
            'trigger.loading': 'Cargando modelos…',
            'trigger.selectAria': 'Seleccionar modelo',
            'trigger.aria': 'Seleccionar modelo; actual: {model}',
            'trigger.ariaEffort': 'Seleccionar modelo; actual: {model}; esfuerzo de razonamiento: {effort}',
            'menu.aria': 'Modelo y esfuerzo de razonamiento',
            'menu.model': 'Modelo',
            'menu.effort': 'Esfuerzo',
            'effort.providerDefault': 'Predeterminado',
            'status.loading': 'Actualizando lista de modelos…',
            'action.reload': 'Recargar',
            'empty.models': 'No hay modelos disponibles.',
            'blocked.composer': 'Este modelo no está disponible; selecciona otro para continuar',
            'empty.efforts': 'Este modelo no ofrece niveles de esfuerzo de razonamiento.'
          },
          conversation: {
            'hint.goal': 'describe el objetivo de una tarea de larga duración',
            'placeholder.default': 'Escribe un mensaje o ejecuta una tarea; / comandos; @ archivos o sesiones',
            'placeholder.unavailable': 'Sesión no disponible',
            'placeholder.hero': 'Describe qué quieres construir; / comandos; @ archivos o sesiones',
            'placeholder.workspace': 'Elige un espacio de trabajo para comenzar',
            'input.commands': 'Agregar archivos o ejecutar comandos',
            'input.file': 'Archivo',
            'input.stop': 'Detener generación',
            'input.send': 'Enviar mensaje',
            'input.send.queue': 'Poner mensaje en cola',
            'input.send.steer': 'Redirigir mensaje',
            'attachment.pending': 'Adjuntos pendientes',
            'attachment.dropTitle': 'Arrastra archivos o imágenes aquí para agregarlos',
            'image.openOriginal': 'Ver original',
            'image.remove': 'Eliminar imagen {name}',
            'image.label': 'Imagen',
            'image.loading': 'Cargando imagen…',
            'file.pending': 'Archivos pendientes',
            'file.remove': 'Eliminar archivo {name}',
            'file.uploading': 'Subiendo…',
            'file.uploadFailed': 'Falló la subida; haz clic para reintentar',
            'file.label': 'Archivo',
            'context.used': 'del contexto utilizado',
            'context.system': 'Prompt del sistema',
            'context.tools': 'Definiciones de herramientas',
            'context.messages': 'Mensajes',
            'hero.headline': 'Hacia lo desconocido',
            'hero.preview': 'Vista previa',
            'hero.chooseWorkspace': 'Elegir espacio de trabajo',
            'session.hierarchy': 'Jerarquía de sesión',
            'todo.title': 'Tareas',
            'todo.progress.done': '{done} completadas',
            'todo.progress.active': '{active} en curso',
            'todo.progress.pending': '{pending} pendientes',
            'ask.rowTitle': 'Hacer pregunta',
            'ask.waiting': 'esperando',
            'ask.cancelled': 'cancelada',
            'ask.interrupted': 'interrumpida',
            'bash.running': 'En ejecución',
            'bash.failed': 'Falló',
            'bash.stopped': 'Detenido',
            'row.running': 'En ejecución',
            'row.failed': 'Falló',
            'row.stopped': 'Detenido',
            'row.inspect': 'Inspeccionar',
            'tool.title.search': 'Buscar',
            'tool.title.read': 'Leer',
            'tool.title.bash': 'Bash',
            'tool.title.write': 'Escribir',
            'tool.title.edit': 'Editar',
            'tool.title.code': 'Código',
            'tool.title.generic': 'Llamada de herramienta',
            'tool.title.inspect': 'Inspeccionar',
            'tool.title.readImage': 'Leer imagen',
            'tool.title.webSearch': 'Buscar en la web',
            'tool.title.webFetch': 'Obtener desde la web',
            'search.noResults': 'Sin resultados',
            'web.noResults': 'No se encontraron resultados',
            'details.running': 'En ejecución…',
            'queue.sending': 'Enviando…',
            'queue.edit': 'Editar mensaje en cola',
            'queue.save': 'Guardar mensaje en cola',
            'queue.cancelEdit': 'Cancelar edición',
            'queue.remove': 'Eliminar mensaje en cola',
            'terminal.running': 'En ejecución',
            'terminal.failed': 'Falló',
            'terminal.done': 'Terminado',
            'terminal.noOutput': 'Sin salida'
          },
          command: {
            'section.add': 'Agregar',
            'section.commands': 'Comandos',
            'label.goal': 'Objetivo',
            'label.plan': 'Plan',
            'label.feedback': 'Comentarios',
            'label.compact': 'Compactar',
            'label.permission': 'Permisos',
            'label.export': 'Exportar',
            'description.goal': 'Definir o ver el objetivo de una tarea de larga duración',
            'description.plan': 'Entrar o salir del modo planificación',
            'description.feedback': 'Registrar comentarios sobre esta sesión',
            'description.compact': 'Compactar el historial antiguo de la conversación',
            'description.permission': 'Cambiar el perfil de permisos',
            'description.export': 'Descargar el registro de la sesión como ZIP',
            'search.placeholder': 'Buscar…',
            'search.aria': 'Filtrar opciones',
            'status.loading': 'Cargando opciones…',
            'status.applying': 'Aplicando…',
            'status.empty': 'Sin opciones'
          },
          goal: {
            'phase.active': 'Objetivo activo',
            'phase.active.disarmed': 'Objetivo inactivo',
            'phase.paused': 'Objetivo pausado',
            'phase.blocked': 'Objetivo bloqueado',
            'objective.aria': 'Objetivo',
            'action.save': 'Guardar objetivo',
            'action.cancel': 'Cancelar edición',
            'action.pause': 'Pausar objetivo',
            'action.resume': 'Reanudar objetivo',
            'action.edit': 'Editar objetivo',
            'action.clear': 'Eliminar objetivo'
          },
          'settings.models': {
            nav: 'Modelos',
            title: 'Modelos',
            intro: 'Ingresa tus claves API para usar modelos de los siguientes proveedores.',
            edit: 'Editar',
            editProvider: 'Editar {provider}',
            remove: 'Eliminar',
            removeProvider: 'Eliminar {provider}',
            deleteTitle: '¿Eliminar {provider}?',
            deleteConfirm: 'Eliminar {provider}',
            deleting: 'Eliminando {provider}…',
            add: 'Agregar proveedor',
            provider: 'Proveedor',
            close: 'Cerrar',
            cancel: 'Cancelar',
            apply: 'Aplicar',
            applying: 'Aplicando…',
            savedProvider: '{provider} guardado.',
            credentialConfigured: 'Clave API configurada',
            credentialMissing: 'Falta la clave API',
            readOnly: 'El documento de configuración es de solo lectura en este despliegue.',
            loadFailed: 'Falló la carga del directorio de proveedores',
            retry: 'Reintentar',
            keyInput: 'Clave API',
            keyPlaceholder: 'Ingresa tu clave API',
            keyStored: 'Configurada; ingresa un nuevo valor para reemplazarla',
            keyEnvLocked: 'Proporcionada por el entorno de inicio (solo lectura)',
            customized: 'Configuración personalizada',
            baseUrl: 'URL base',
            baseUrlDefault: 'Predeterminado del proveedor',
            models: 'Modelos',
            modelsInherited: 'Usando los valores predeterminados del adaptador',
            modelsCustomized: 'Catálogo de modelos personalizado',
            resetModels: 'Restaurar predeterminados',
            model: 'Modelo',
            modelId: 'ID del modelo',
            modelName: 'Nombre visible',
            contextWindow: 'Ventana de contexto',
            maxTokens: 'Máximo de tokens de salida',
            modelAdvanced: 'Opciones del modelo',
            modelInputTypes: 'Tipos de entrada',
            modelInputText: 'Texto',
            modelInputImage: 'Imagen',
            addModel: 'Agregar modelo',
            removeModel: 'Eliminar modelo',
            fetchModels: 'Obtener modelos disponibles',
            fetching: 'Consultando al proveedor…',
            fetchSearch: 'Buscar modelos',
            fetchNoMatches: 'No hay modelos coincidentes.',
            fetchSelectAll: 'Seleccionar todos',
            fetchDeselectAll: 'Deseleccionar todos',
            fetchAdopt: 'Agregar seleccionados',
            customAdd: 'Agregar proveedor personalizado',
            customTitle: 'Proveedor personalizado',
            customTag: 'Personalizado',
            customDisplayName: 'Nombre visible',
            create: 'Crear proveedor',
            creating: 'Creando…',
            welcomeContinue: 'Continuar',
            onboardingTitle: 'Agrega una clave API para comenzar',
            onboardingDescription: 'Configura el proveedor oficial de DeepSeek para comenzar.',
            onboardingLater: 'Configurar después',
            onboardingSave: 'Guardar y continuar',
            onboardingSaving: 'Guardando…',
            keyRequired: 'Ingresa una clave API para continuar.'
          }
        }

        for (const [namespace, dictionary] of Object.entries(dictionaries)) {
          ctx.effect(
            () => ctx.locale.register(namespace, 'es', dictionary),
            `master-cas: Spanish dictionary ${namespace}`
          )
        }
      }
    }
  }
})
